### ISSUE TITLE
Typo #01 in CSS lesson 09. Spellcheck

### ISSUE THREAD

**Issue by MilanGrujicic** [codedex-io/css-101#23]
Hello team,

I would like to report a typo in this [page](https://www.codedex.io/css/09-spellcheck).

The sentence `Three common ways to align text is` should be replaced with `Three common ways to align are`. 

The context suggests that the sentence is about the three common ways to align text.

Please see the attached image for more context. 👇
![Screenshot_2023-10-28_19-51-23](https://github.com/codedex-io/css-101/assets/48260426/5910a088-8b69-4ee7-b8f0-74ece4886751)

**Comment by sonnynomnom** [comment]
+2 complete! https://github.com/codedex-io/curriculum/commit/e0f357097f0b8789227d8338dd0dc235585f7648
