### ISSUE TITLE
Typo #02 in CSS file 09-spellcheck/index.html

### ISSUE THREAD

**Issue by MilanGrujicic** [codedex-io/css-101#37]
Hello team,

I would like to report a typo in this [file](https://github.com/codedex-io/css-101/blob/main/2-properties/09-spellcheck/index.html).

The string 'overthe' should be replaced with 'over the'.

Please see the attached picture for more context.
![Screenshot_2023-10-30_13-29-47](https://github.com/codedex-io/css-101/assets/48260426/ee73a5be-d46c-47dd-ab1e-e54aa16f18ed)

**Comment by sonnynomnom** [comment]
not a bug
