### ISSUE TITLE
Typos from The Origins II: CSS

### ISSUE THREAD

**Issue by MilanGrujicic** [codedex-io/css-101#7]
Hello team,

Please find below a list of typos from The Origins II: CSS lessons.

### 02. Syntax
- Replace 'look' with 'looks', see picture typo_I.png. 👇
![typo_I](https://github.com/codedex-io/css-101/assets/48260426/8b68fa8c-1d83-4f68-9624-c7cdb43a6a4b)

- Add 'it' after 'surrounding', see picture typo_II.png. 👇
![typo_II](https://github.com/codedex-io/css-101/assets/48260426/d9374c7e-45ae-4325-a6f4-d53497dd50b8)

**Comment by sonnynomnom** [comment]
Updated!!!
